name: Feature Request
description: Please explain what is in your mind, we would like to hear it!
labels: "feature"
assignees: "Neodevils"

body:
  - type: markdown
    attributes:
      value: |
        Please explain what is in your mind, we would like to hear it!

  - type: dropdown
    id: type
    attributes:
      label: Featuring Type
      description: Please select a type of feature you want to request.
      options:
        - Slash Command
        - User Command
        - Message Command
        - Button Command
        - Select Menu Command
        - Modal Command
    validations:
      required: true

  - type: textarea
    id: explaining
    attributes:
      label: So, what is it about?
      description: Please describe what you're requesting for. So, we can understand your request better and work on it faster!
      placeholder: It's about...
    validations:
      required: true
