name: Build and Publish Dist Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare dist-build branch
        run: |
          git checkout -B dist-build

          # İstenmeyen dosyaları sil
          git rm -rf src tsconfig.json

          # .gitignore ve package.json kalabilir, istersen onları da tut
          # git rm --cached .gitignore  # istersen yorum satırından çıkar

          git add .
          git commit -m "Build dist only and cleanup [skip ci]" || echo "No changes to commit"

          git push --force origin dist-build
